name: Build JDK 17
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 117
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up testcontainers
        run: docker image pull testcontainers/ryuk:0.3.0

      - name: Unit and Integration tests
        run: mvn -B -Pit verify
